import type { Metadata } from "next";
import Spline from "next/font/local";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.scss";

const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({ variable: "--font-geist-mono", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Note handler",
  description: "Generated by create next app",
};

const SplineFont = Spline({
  src: "../../public/font/Spline.ttf",
  display: "swap",
  variable: "--font-spline",
});

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={SplineFont.className}>{children}</body>
    </html>
  );
}
